vk/urls.py
from django.conf.urls import url

from vk import views

app_name = 'vk'

urlpatterns = [
    url(r'^$', views.app_index, name='index'),
    url(r'^donate/$', views.donate, name='make_donate')
]

templates/app/before.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <div class="page-header text-center">
                <h1>Vdonate</h1>
            </div>
        </div>

        {% if user %}
            <div class="col-sm-offset-4 col-sm-4">
                <img src="{{ user.photo_200 }}" class="img-circle img-responsive center" width="150">
                <h3 class="text-center">{{ user.first_name }} {{ user.last_name }}</h3>
            </div>
        {% endif %}
        <div class="col-sm-offset-4 col-sm-4">
            {% if status == 'success' %}
                <div class="alert alert-success" role="alert">
                    <p><b>Отлично!</b> Спасибо вам большое за поддержку!</p>
                </div>
                <a class="btn btn-info before-btn" href="https://vk.com/club{{ group_id }}">На страницу сообщества</a>
            {% elif status == 'fail' %}
                <div class="alert alert-danger" role="alert">
                    <p><b>Увы!</b> {{ error }}.</p>
                </div>
                <a class="btn btn-success before-btn retry-payment" href="{% url 'vk:index'%}">Попробовать ещё раз</a>
                <a class="btn btn-info before-btn" href="https://vk.com/club{{ group_id }}">На страницу сообщества</a>
            {% endif %}


        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/app/index.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
            <div class="page-header text-center">
                <h1>Vdonate</h1>
            </div>
        </div>

        {% if user %}
            <div class="col-sm-offset-4 col-sm-4">
                <img src="{{ user.photo_200 }}" class="img-circle img-responsive center" width="150">
                <h3 class="text-center">{{ user.first_name }} {{ user.last_name }}</h3>
            </div>
        {% endif %}
        <div class="col-sm-offset-4 col-sm-4">
            {% if success == 1 %}
                <div class="alert alert-success" role="alert">
                    <p><b>Oh!</b> It is a good joke!</p>
                </div>
            {% elif success == 2 %}
                <div class="alert alert-danger" role="alert">
                    <p><b>Hmm..</b> Try again!</p>
                </div>
            {% endif %}
            {% if user %}
                {% if not success %}
                <form method="POST" action="{% url 'vk:make_donate' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" name="amount" id="inputAmount" placeholder="Сумма">
                    </div>
                    <div class="form-group">
                        <textarea maxlength="100" class="form-control" name="comment" rows="3" id="inputComment" placeholder="Ваш комментарий"></textarea>
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-success">Отправить</button>
                    </div>
                </form>
                {% endif %}
            {% else %}
                <h3 class="text-center error">Если Вы пришли из сообщества <a href="https://vk.com">vk.com</a> и видите эту надпись - значит вашего сообщества
                нет в нашей системе, напишите нам <a href="mailto:support@vdonate.pro">support@vdonate.pro</a> и мы Вам поможем.</h3>
            {% endif %}
            </div>

    </div>
{% endblock %}

{% block footer %}
{% endblock %}