vk/urls.py
from django.conf.urls import url

from vk import views

app_name = 'vk'

urlpatterns = [
    url(r'^$', views.app_index, name='index'),
    url(r'^donate/$', views.donate, name='make_donate')
]

web/urls.py
from django.conf.urls import url

from web.views import index, get_covers, payment, send_email

app_name = 'web'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^covers/(?P<uuid>[0-9\-a-z]+)/$', get_covers, name='covers'),
    url(r'^send-email/$', send_email, name='send-email'),
    url(r'^payment/$', payment.process),
    url(r'^payment/success/$', payment.success),
    url(r'^payment/fail/$', payment.fail),
]

templates/web/banner-1.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>Banner 1</title>
		<meta name="theme-color" content="#ffffff">
		<link href="css/all-styles.css" rel="stylesheet"/>
		<link href="css/app.css" rel="stylesheet"/>
	</head>
	<body class="page">
		<div class="poster-wrapper poster-wrapper--type-1">
			<div class="donations-1">
				<div class="donations-1__item">
					<div class="donations-1__left">
						<div class="donations-1__avatar"><img src="images/draft-photo--type-1.png" alt="" role="presentation"/>
						</div>
						<div class="donations-1__content">
							<div class="donations-1__name">Денисов Андрей
							</div>
							<div class="donations-1__message">Если нужно сделать быстрый wireframe для проекта, то этот ресурс поможет. Расширенная версия вдобавок включает в себя ряд дополнительных
							</div>
						</div>
					</div>
					<div class="donations-1__right">
						<div class="donations-1__donate"><span>120$</span>
						</div>
					</div>
				</div>
				<div class="donations-1__item">
					<div class="donations-1__left">
						<div class="donations-1__avatar"><img src="images/draft-photo--type-1.png" alt="" role="presentation"/>
						</div>
						<div class="donations-1__content">
							<div class="donations-1__name">Денисов Андрей
							</div>
							<div class="donations-1__message">Если нужно сделать быстрый wireframe для проекта, то этот ресурс поможет. Расширенная версия вдобавок включает в себя ряд дополнительных
							</div>
						</div>
					</div>
					<div class="donations-1__right">
						<div class="donations-1__donate"><span>120$</span>
						</div>
					</div>
				</div>
				<div class="donations-1__item">
					<div class="donations-1__left">
						<div class="donations-1__avatar"><img src="images/draft-photo--type-1.png" alt="" role="presentation"/>
						</div>
						<div class="donations-1__content">
							<div class="donations-1__name">Денисов Андрей
							</div>
							<div class="donations-1__message">Если нужно сделать быстрый wireframe для проекта, то этот ресурс поможет. Расширенная версия вдобавок включает в себя ряд дополнительных
							</div>
						</div>
					</div>
					<div class="donations-1__right">
						<div class="donations-1__donate"><span>120$</span>
						</div>
					</div>
				</div>
			</div>
			<div class="progress-1">
				<div class="progress-1__bar">
				</div>
				<div class="progress-1__bar">
				</div>
				<div class="progress-1__bar">
				</div>
				<div class="progress-1__bar">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__bar progress-1__bar--fill">
				</div>
				<div class="progress-1__percent">60%
				</div>
			</div>
			<div class="sponsor">
				<div class="sponsor__logo"><img src="images/draft-logo.png" alt="" role="presentation"/>
				</div>
				<div class="sponsor__desc">универмаг
				</div>
				<div class="sponsor__title">Tsvetnoy Central Market
				</div>
			</div>
		</div>
		<script src="js/common.js"></script>
		<script src="js/app.js"></script>
	</body>
</html>

templates/web/banner-3.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>Banner 3</title>
		<meta name="theme-color" content="#ffffff">
		<link href="{% static 'web/css/all-styles.css' %}" rel="stylesheet"/>
		<link href="{% static 'web/css/app.css' %}" rel="stylesheet"/>
	</head>
	<body class="page">
		<div class="poster-wrapper poster-wrapper--type-3">
			<div class="sponsor">
				<div class="sponsor__logo"><img src="{% static 'web/img/draft-logo.png' %}" alt="" role="presentation"/>
				</div>
				<div class="sponsor__desc">{{ group.name }}
				</div>
				<div class="sponsor__title">
				</div>
			</div>
			<div class="donations">
                {% for donate in donates %}
				<div class="donations__item donations__item--{% cycle 'pink' 'yellow' 'purple' %}">
					<div class="donations__left">
						<div class="donations__avatar"><img width="70px" src="{% if donate.avatar %}{{ donate.avatar }}{% else %}{{ default_url }}{% endif %}" alt="" role="presentation"/>
						</div>
						<div class="donations__content">
							<div class="donations__name">{{ donate.first_name }} {{ donate.last_name }}
							</div>
							<div class="donations__message">{{ donate.text }}
							</div>
						</div>
					</div>
					<div class="donations__right">
						<div class="donations__donate">{{ donate.amount }}
						</div>
					</div>
				</div>
                {% endfor %}
{#				<div class="donations__item donations__item--yellow">#}
{#					<div class="donations__left">#}
{#						<div class="donations__avatar"><img src="images/draft-photo.png" alt="" role="presentation"/>#}
{#						</div>#}
{#						<div class="donations__content">#}
{#							<div class="donations__name">Денисов Андрей#}
{#							</div>#}
{#							<div class="donations__message">Если нужно сделать быстрый wireframe для проекта то#}
{#							</div>#}
{#						</div>#}
{#					</div>#}
{#					<div class="donations__right">#}
{#						<div class="donations__donate">120$#}
{#						</div>#}
{#					</div>#}
{#				</div>#}
{#				<div class="donations__item donations__item--purple">#}
{#					<div class="donations__left">#}
{#						<div class="donations__avatar"><img src="images/draft-photo.png" alt="" role="presentation"/>#}
{#						</div>#}
{#						<div class="donations__content">#}
{#							<div class="donations__name">Денисов Андрей#}
{#							</div>#}
{#							<div class="donations__message">Если нужно сделать быстрый wireframe для проекта то#}
{#							</div>#}
{#						</div>#}
{#					</div>#}
{#					<div class="donations__right">#}
{#						<div class="donations__donate">120$#}
{#						</div>#}
{#					</div>#}
{#				</div>#}
			</div>
            {% if target_percents %}
			<div class="progress" style="--progress-bar: {{ target_percents }}%;">
				<div class="progress__outline">
					<svg>
						<circle r="170" cx="50%" cy="50%"></circle>
					</svg>
				</div>
				<div class="progress__circle">
					<div class="progress__text">{{ target_percents }} %
					</div>
				</div>
			</div>
            {% endif %}
		</div>
		<script src="{% static 'web/js/common.js' %}"></script>
		<script src="{% static 'web/js/app.js' %}"></script>
	</body>
</html>

templates/web/cover.html
{# Django template #}
{% load staticfiles %}

<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Document</title>
	<link href="https://fonts.googleapis.com/css?family=Roboto&amp;subset=cyrillic" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'web/css/covers/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'web/css/covers/style.css' %}">
</head>
<body>
	<div class="wrapper">
		<div class="left">
			<div class="chat">
                {% for donate in donates %}
				<div class="chat__item">
					<div class="chat__left">
						<div class="chat__avatar">
							<img src="{% if donate.avatar %}{{ donate.avatar }}{% else %}{{ default_url }}{% endif %}" alt="" />
						</div>
						<!-- /.__avatar -->
					</div>
					<!-- /.chat__left -->
					<div class="chat__right">
						<div class="message">
							<div class="message__nick">{{ donate.first_name }} {{ donate.last_name }}</div>
							<!-- /.message__nick -->
							<div class="message__text">{{ donate.text }}</div>
							<!-- /.message__text -->
							<div class="message__points">
								<div class="points">
									<div class="points__score">{{ donate.amount }}</div>
									<!-- /.points__score -->
									<div class="points__char">Р</div>
									<!-- /.points__char -->
								</div>
								<!-- /.points -->
							</div>
							<!-- /.message__points -->
						</div>
						<!-- /.message -->
					</div>
					<!-- /.chat__right -->
				</div>
                {% endfor %}
{#				<div class="chat__item">#}
{#					<div class="chat__left">#}
{#						<div class="chat__avatar">#}
{#							<img src="images/avatar.jpg" alt="" />#}
{#						</div>#}
{#						<!-- /.__avatar -->#}
{#					</div>#}
{#					<!-- /.chat__left -->#}
{#					<div class="chat__right">#}
{#						<div class="message">#}
{#							<div class="message__nick">Никита Исаев</div>#}
{#							<!-- /.message__nick -->#}
{#							<div class="message__text">Это быстрый и настраиваемый веб-браузер для продвинутых пользователей, созданный людьми, которые стояли у истоков Оpera. Называемый “Браузер для наших друзей”, Vivaldi строился с Vivaldi</div>#}
{#							<!-- /.message__text -->#}
{#							<div class="message__points">#}
{#								<div class="points">#}
{#									<div class="points__score">2 233</div>#}
{#									<!-- /.points__score -->#}
{#									<div class="points__char">П</div>#}
{#									<!-- /.points__char -->#}
{#								</div>#}
{#								<!-- /.points -->#}
{#							</div>#}
{#							<!-- /.message__points -->#}
{#						</div>#}
{#						<!-- /.message -->#}
{#					</div>#}
{#					<!-- /.chat__right -->#}
{#				</div>#}
{#				<div class="chat__item">#}
{#					<div class="chat__left">#}
{#						<div class="chat__avatar">#}
{#							<img src="images/avatar.jpg" alt="" />#}
{#						</div>#}
{#						<!-- /.__avatar -->#}
{#					</div>#}
{#					<!-- /.chat__left -->#}
{#					<div class="chat__right">#}
{#						<div class="message">#}
{#							<div class="message__nick">Никита Исаев</div>#}
{#							<!-- /.message__nick -->#}
{#							<div class="message__text">Это быстрый и настраиваемый веб-браузер для продвинутых пользователей, созданный людьми, которые стояли у истоков Оpera. Называемый “Браузер для наших друзей”, Vivaldi строился с Vivaldi</div>#}
{#							<!-- /.message__text -->#}
{#							<div class="message__points">#}
{#								<div class="points">#}
{#									<div class="points__score">2 233</div>#}
{#									<!-- /.points__score -->#}
{#									<div class="points__char">П</div>#}
{#									<!-- /.points__char -->#}
{#								</div>#}
{#								<!-- /.points -->#}
{#							</div>#}
{#							<!-- /.message__points -->#}
{#						</div>#}
{#						<!-- /.message -->#}
{#					</div>#}
{#					<!-- /.chat__right -->#}
{#				</div>#}
				<!-- /.chat__item -->
			</div>
			<!-- /.chat -->
		</div>
		<div class="right">
			<div class="status">
				<div class="status__text">{{ target.description }}</div>
				<!-- /.status__text -->
			</div>
			<!-- /.status -->
            {% if target_percents %}
			<div class="progress">
				<div class="progress__bar" style="width: {{ target_percents }}%"></div>
				<!-- /.progress__bar -->
				<div class="progress__text">{{ target_percents }}%</div>
				<!-- /.progress__text -->
			</div>
            {% endif %}
			<!-- /.progress -->
		</div>
	</div>
</body>
</html>

templates/web/cover2.html
{# Django template #}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>VK-app</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="{% static 'web/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'web/css/style.css' %}?=v2" rel="stylesheet">
    <link href="{% static 'web/css/cover.css' %}?=v4" rel="stylesheet">
</head>
<body>
    <div class="cover-bg">
        {% for donate in donates %}
        <div class="donates-container">
            <div class="img-container">
                <img src="{{ MEDIA_URL }}{{ donate.avatar }}" class="img-circle" width="105px">
            </div>
            <div class="text-container {% cycle 'first' 'second' 'third' %}">
                <p class="username"><b>{{ donate.first_name }} {{ donate.last_name }}</b> <span style="color: #761c19">+{{ donate.amount }}</span></p>
                <p class="comment">{{ donate.text }}</p>
            </div>
        </div>
        {% endfor %}
        {% if target.amount %}
        <div class="target">
            <h1>{{ target.donates_sum }}/{{ target.amount }}</h1>
        </div>
        {% endif %}
    </div>
    <script src="{% static 'web/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/web/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>VDonate - Сбор пожертвований на благие дела!</title>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, minimum-scale=1.0, initial-scale=1.0" />
    <link href="{% static 'web/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'web/css/style.css' %}?=v2" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="" />

    <link href="{% static 'web/css/main.css' %}" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css' />

    <script type="text/javascript" src="{% static 'web/js/jquery-1.7.2.js' %}"></script>
    <script type="text/javascript" src="{% static 'web/js/custom.js' %}"></script>
</head>
<body>
	<!-- Header
		============================= -->
	<div id="header">
        <div class="inner">

            <!-- Logo -->
            <h1 class="logo left"><a href="#">Vdonate</a></h1><!-- .logo-->

            <!-- Nav Menu -->
            <ul class="nav-menu right">
                <li class="current"><a href="#">наверх</a></li>
                <li><a href="#services">услуги</a></li>
                <li><a href="#about">о нас</a></li>
                <li><a href="#contact">контакты</a></li>
            </ul><!-- .nav-menu-->

        </div><!-- .inner -->
	</div><!-- #header -->
	<!-- End Header -->


<!--
	<div id="slider" class="theme-default">
        <div class="inner">

        	<div class="nivo-slider nivoSlider">
                <a href=""><img src="images/slides/singolo-slide1.jpg" alt="#" /></a>
                <img src="images/slides/singolo-slide2.jpg" alt="#" />
            </div>

        </div>
	</div>
	 -->


	<!-- Services
		============================= -->
	<div id="services">
        <div class="inner">

        	<h2>Что предоставляет наш сервис</h2>
            <h3>Мы предоставляем возможность сообществам социальной сети <a href="https://vk.com">Вконтакте</a> собирать пожертования.</h3>

            <ul>
            	<li>
                	<span class="li_pen"></span>
                    <h4>Индивидуальный подход</h4>
                    <p>Подготовим уникальную обложку для вашего сообщества.</p>
                </li>


                <li>
                	<span class="li_bulb"></span>
                    <h4>Удобство использования</h4>
                    <p>Прозрачная система остлеживания донатов.</p>
                </li>


                <li>
                	<span class="li_phone"></span>
                    <h4>Адаптивный дизайн</h4>
                    <p>Наше приложение красиво выглядит и на мобильных и на Desktop приложениях</p>
                </li>


            </ul>

        </div><!-- .inner -->
	</div><!-- #services -->
	<!-- End Services -->

	<!-- About
		============================= -->
	<div id="about">
        <div class="inner">

        	<!-- Title -->
        	<h2>О Vdonate</h2>

            <!-- Short Description -->
            <h3>Вы размещаете наше приложение у себя в сообществе. Ваши подписчики запускают приложение и оказываются на странице с формой, в которой они вводят сумму доната и комментарий (возможность комментирования настраивается). Дальше мы перенаправляем пользователя на страницу платёжки, в которой они совершают платёж. При успешном платеже наша система меняет обложку вашего сообщества, добавляя информацию о новом донате.</h3>

        </div><!-- .inner -->
	</div><!-- #about -->
	<!-- End About -->


	<!-- Contact
		============================= -->
	<div id="contact">
        <div class="inner">

        	<!-- Title -->
        	<h2>Оставьте заявку</h2>

            <!-- Short Description -->
            <h3>Оставьте свою заявку и мы обязательно с вами свяжимся.</h3>

            <ul>
            	<li>
                	<form action="{% url 'web:send-email'%}" method="post">
                        {% csrf_token %}
                        <input name="name" class="" type="text" placeholder="Имя"/>

                        <input name="email" class="" type="email" placeholder="Email" required/>

                        <textarea name="comment" cols="" rows="" placeholder="Ваше сообщение" required></textarea>

                        <input type="submit" value="Отправить" name="subscribe" class="submitbtn" />

                    </form>
                </li>

                <li>
                	<h4>Контатктная информация</h4>

                    <span><i class="icon-mail"></i>support@vdonate.pro</span>
                </li>
            </ul>


        </div><!-- .inner -->
	</div><!-- #contact -->
	<!-- End Contact -->


	<!-- Footer
		============================= -->
	<div id="footer">
        <div class="inner">

        	<p class="left">© Copyright 2017 by <a href="">3PSI</a></p>
            <div style="display: inline-block; float: right">
                <a href="//www.free-kassa.ru/"><img src="//www.free-kassa.ru/img/fk_btn/6.png"></a>
            </div>

<!--             <ul>
            	<li>
                    <a href=""><span class="icon-facebook"></span></a>
                    <a href=""><span class="icon-gplus"></span></a>
                    <a href=""><span class="icon-twitter"></span></a>
                    <a href=""><span class="icon-linkedin"></span></a>
                </li>
            </ul> -->

        </div><!-- .inner -->
	</div><!-- #footer -->
	<!-- End Footer -->

    <a href="" class="go-top">Наверх!</a>

</body>
</html>